version: "2"
services:
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=64mb
    container_name: livestock_auction-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_DATABASE: "livestock_auction"
    volumes:
      - my_datavolume:/var/lib/mysql

  livestock-auction-api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3001:3001
    depends_on:
      - mysql

volumes:
  my_datavolume: