org: merlin2010
app: myapp
service: auction-server
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0ea2ccb06a0828282
    subnetIds:
      - subnet-cdf7d1aa
      - subnet-4080984f
  environment:
    NODE_ENV: production
    privateKey: ${self:custom.environment.publicKey}
    publicKey: ${self:custom.environment.privateKey}
    password: ${self:custom.environment.password}
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/graphql.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
    - http:
        path: playground
        method: get
        cors: true